language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true


before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - make flake8
  - make mypy
  - make test
  - make doc8
  - make check
  - make safety-check

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
